{% set version = '1.6.0' %}

package:
  name: r-igraph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/igraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/igraph/igraph_{{ version }}.tar.gz
  sha256: 410ecc37fb38e72079dc72f839bde19093100a422729c343e0b2523df6453bb8

build:
  # If this is a new build for the same version, increment the build number.
  number: 1
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:

  host:
    - r-base
    - r-cli
    - r-lifecycle
    - r-magrittr
    - r-matrix
    - r-pkgconfig
    - r-rlang
    - r-cpp11

  run:
    - r-base
    - r-cli
    - r-lifecycle
    - r-magrittr
    - r-matrix
    - r-pkgconfig
    - r-rlang
    - r-cpp11


test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('igraph')"           # [not win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=igraph
  license: GPL-3
  summary: R package of the igraph network analysis library.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
