package:
  name: 'bioconductor-data-packages'
  version: '20240709'
source:
build:
  number: '0'
  noarch: generic
  run_exports:
    - {{ pin_subpackage("bioconductor-data-packages", max_pin=None) }}
requirements:
  run:
    - r-base
    # - curl
    - yq
test:
  commands:
    - yq --help
about:
  home: "https://github.com/bioconda/bioconda-utils"
  license: 'MIT'
  summary: 'A package to enable downloading and installation of Bioconductor data packages'
  description: 'wget used instead of curl. curl keeps failing sometimes with errors like `curl: error while loading shared libraries: libssl.so.1.0.0`'
