{% set name = "r-seuratdata" %}
{% set version = "2023.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/satijalab/seurat-data
  git_rev: 4dc08e022f51c324bc7bf785b1b5771d2742701d  # on Nov 4, 2023

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-cli
    - r-crayon
    - r-rappdirs
    - r-seurat
    - r-seuratobject
  run:
    - r-base
    - r-cli
    - r-crayon
    - r-rappdirs
    - r-seurat
    - r-seuratobject

test:
  commands:
    - $R -e 'library(SeuratData)'

about:
  home: https://github.com/satijalab/seurat-data
  dev_url: https://github.com/satijalab/seurat-data
  license: GPL-3
  license_file: LICENSE
  summary: |
    SeuratData is a mechanism for distributing datasets in the form of Seurat objects
    using R's internal package and data management systems.
  description: |
    Single cell RNA sequencing datasets can be large, consisting of matrices
    that contain expression data for several thousand features across several
    thousand cells. This package is designed to easily install, manage, and learn
    about various single-cell datasets, provided Seurat objects and distributed
    as independent packages.
  license_family: GPL3
