{% set version = '5.0.1' %}

package:
  name: r-seurat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Seurat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Seurat/Seurat_{{ version }}.tar.gz
  sha256: 0713b434be5bf14fcea068fbfc632ba15bebdec1007f1f48effd0dbb95c5150d

build:
  number: 1
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:

  host:
    - r-base
    - r-seuratobject
    - r-cluster
    - r-cowplot
    - r-fastdummies
    - r-fitdistrplus
    - r-future
    - r-future.apply
    - r-generics
    - r-ggplot2
    - r-ggrepel
    - r-ggridges
    - r-httr
    - r-ica
    - r-igraph
    - r-irlba
    - r-jsonlite
    - r-kernsmooth
    - r-leiden
    - r-lifecycle
    - r-lmtest
    - r-mass
    - r-matrix
    - r-matrixstats
    - r-miniui
    - r-patchwork
    - r-pbapply
    - r-plotly
    - r-png
    - r-progressr
    - r-purrr
    - r-rann
    - r-rcolorbrewer
    - r-rcpp
    - r-rcppannoy
    - r-rcpphnsw
    - r-reticulate
    - r-rlang
    - r-rocr
    - r-rspectra
    - r-rtsne
    - r-scales
    - r-scattermore
    - r-sctransform
    - r-shiny
    - r-spatstat.explore
    - r-spatstat.geom
    - r-tibble
    - r-uwot

  run:
    - r-base
    - r-seuratobject
    - r-cluster
    - r-cowplot
    - r-fastdummies
    - r-fitdistrplus
    - r-future
    - r-future.apply
    - r-generics
    - r-ggplot2
    - r-ggrepel
    - r-ggridges
    - r-httr
    - r-ica
    - r-igraph
    - r-irlba
    - r-jsonlite
    - r-kernsmooth
    - r-leiden
    - r-lifecycle
    - r-lmtest
    - r-mass
    - r-matrix
    - r-matrixstats
    - r-miniui
    - r-patchwork
    - r-pbapply
    - r-plotly
    - r-png
    - r-progressr
    - r-purrr
    - r-rann
    - r-rcolorbrewer
    - r-rcpp
    - r-rcppannoy
    - r-rcpphnsw
    - r-reticulate
    - r-rlang
    - r-rocr
    - r-rspectra
    - r-rtsne
    - r-scales
    - r-scattermore
    - r-sctransform
    - r-shiny
    - r-spatstat.explore
    - r-spatstat.geom
    - r-tibble
    - r-uwot


test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Seurat')"           # [not win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=Seurat
  license: MIT
  summary: R toolkit for single cell genomics
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

# The original CRAN metadata for this package was:

# Package: RVenn
# Type: Package
# Title: Set Operations for Many Sets
# Version: 1.1.0
# Authors@R: person("Turgut Yigit", "Akyol", email = "tyakyol@gmail.com", role = c("aut", "cre"))
# Maintainer: Turgut Yigit Akyol <tyakyol@gmail.com>
# Description: Set operations for many sets. The base functions for set operations in R can be used for only two sets. This package uses 'purr' to find the union, intersection and difference of three or more sets. This package also provides functions for pairwise set operations among several sets. Further, based on 'ggplot2' and 'ggforce', a Venn diagram can be drawn for two or three sets. For bigger data sets, a clustered heatmap showing presence/absence of the elements of the sets can be drawn based on the 'pheatmap' package. Finally, enrichment test can be applied to two sets whether an overlap is statistically significant or not.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: ggforce (>= 0.2.1), ggplot2 (>= 3.0.0), magrittr (>= 1.5), purrr (>= 0.2.5), methods (>= 3.5.1), rlang (>= 0.2.2), vegan (>= 2.5.2), pheatmap (>= 1.0.10)
# RoxygenNote: 6.1.1
# Collate: 'Construct.R' 'Plot.R' 'SetOperations.R' 'RVenn.R' 'Enrichment.R' 'Pairs.R' 'Heatmap.R'
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-18 20:55:18 UTC; tyakyol
# Author: Turgut Yigit Akyol [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-07-18 21:40:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
