{% set version = '2023.12.16' %}

package:
  name: r-presto
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/immunogenomics/presto
  git_rev: 31dc97fed5e2e7fc323ae4af62f72181cc51d9a3 # on 2023.4.30

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 1
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, V8
requirements:

  build:
    - r-base
    - r-rcpp
    - r-data.table
    - r-dplyr
    - r-tidyr
    - r-purrr
    - r-tibble
    - r-matrix
    - r-rlang
    - r-rcpparmadillo

  run:
    - r-base
    - r-rcpp
    - r-data.table
    - r-dplyr
    - r-tidyr
    - r-purrr
    - r-tibble
    - r-matrix
    - r-rlang
    - r-rcpparmadillo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('presto')"           # [not win]
    - "\"%R%\" -e \"library('presto')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/immunogenomics/presto
  license: GPL-3
  summary: Fast Wilcoxon and auROC.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    - DESCRIPTION
