{% set version = '0.2.0' %}

package:
  name: r-slugify
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/hrbrmstr/slugify
  git_rev: 6bc49180418ff8e43a97154cc2d6a6c01d1e5138 # on 2021.05.17

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 1
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, V8
requirements:

  build:
    - r-base
    - r-stringi

  run:
    - r-base
    - r-stringi

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('slugify')"           # [not win]
    - "\"%R%\" -e \"library('slugify')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hrbrmstr/slugify
  license: MIT
  summary: Slugify strings in R
  license_family: MIT
  license_file:
    - LICENSE
