{% set name = "bioconductor-seqarray" %}
{% set version = "1.44.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/zhengxwen/SeqArray
  git_rev: 661eb0aa3b195df0a855a827306349bc7db44bd0  # 5/16/2024

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
    host:
        - bioconductor-iranges
        - bioconductor-genomicranges
        - bioconductor-genomeinfodb
        - bioconductor-biostrings
        - bioconductor-s4vectors
    run:
        - bioconductor-iranges
        - bioconductor-genomicranges
        - bioconductor-genomeinfodb
        - bioconductor-biostrings
        - bioconductor-s4vectors

test:
    commands:
        - $R -e 'library(SeqArray)'

about:
  home: https://github.com/zhengxwen/SeqArray
  dev_url: https://github.com/zhengxwen/SeqArray
  license: GPL-3
  license_file: DESCRIPTION
  summary: 'Data Management of Large-scale Whole-genome Sequence Variant Calls'
  description: |
    Data management of whole-genome sequence variant calls with hundreds of thousands
    of individuals: genotypic data (e.g., SNVs, indels and structural variation calls)
    and annotations in SeqArray GDS files are stored in an array-oriented and
    compressed manner, with efficient data access using the R programming language.
    The SeqArray package is built on top of Genomic Data Structure (GDS) data format,
    and defines required data structure for a SeqArray file. GDS is a flexible and
    portable data container with hierarchical structure to store multiple scalable
    array-oriented data sets. It is suited for large-scale datasets, especially for
    data which are much larger than the available random-access memory. It also offers
    the efficient operations specifically designed for integers of less than 8 bits,
    since a diploid genotype usually occupies fewer bits than a byte. Data compression
    and decompression are available with relatively efficient random access.
    A high-level R interface to GDS files is available in the package gdsfmt.
  license_family: GPL
