# by rattler-build

context:
  name: bioconductor-seqarray
  version: 1.42.4
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://git.bioconductor.org/packages/SeqArray
  # branch: RELEASE_3_18
  rev: ae2387745ec0a9af6bde8c331e86587cd7fbe4a5  # 4/3/2024

build:
  number: ${{ build_number }}
  script:
    - R CMD INSTALL --build .

requirements:
  host:
      - bioconductor-iranges
      - bioconductor-genomicranges
      - bioconductor-genomeinfodb
      - bioconductor-biostrings
      - bioconductor-s4vectors
      - bioconductor-gdsfmt
  run:
      - bioconductor-iranges
      - bioconductor-genomicranges
      - bioconductor-genomeinfodb
      - bioconductor-biostrings
      - bioconductor-s4vectors
      - bioconductor-gdsfmt

tests:
  - script:
    - R -e 'library(SeqArray)'

about:
  homepage: https://github.com/zhengxwen/SeqArray
  license: 	GPL-3.0-or-later
  license_file: DESCRIPTION
  summary: 'Data Management of Large-scale Whole-genome Sequence Variant Calls'
  description: |
    Data management of whole-genome sequence variant calls with hundreds of thousands
    of individuals: genotypic data (e.g., SNVs, indels and structural variation calls)
    and annotations in SeqArray GDS files are stored in an array-oriented and
    compressed manner, with efficient data access using the R programming language.
    The SeqArray package is built on top of Genomic Data Structure (GDS) data format,
    and defines required data structure for a SeqArray file. GDS is a flexible and
    portable data container with hierarchical structure to store multiple scalable
    array-oriented data sets. It is suited for large-scale datasets, especially for
    data which are much larger than the available random-access memory. It also offers
    the efficient operations specifically designed for integers of less than 8 bits,
    since a diploid genotype usually occupies fewer bits than a byte. Data compression
    and decompression are available with relatively efficient random access.
    A high-level R interface to GDS files is available in the package gdsfmt.
