package:
  name: bioconductor-gdsfmt
  version: 1.38.0

source:
  git_url: https://git.bioconductor.org/packages/gdsfmt
  git_rev: 47ebf725814d52ff0c42d6fce908dbd11c8b50b3  # 10/24/2023

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
    host:
      - r-base=4.2
    run:
      - r-base=4.2

test:
    commands:
        - $R -e 'library(gdsfmt)'

about:
  home: https://github.com/zhengxwen/gdsfmt
  dev_url: https://github.com/zhengxwen/gdsfmt
  license: LGPL-3
  license_file: DESCRIPTION
  summary: 'R Interface to CoreArray Genomic Data Structure (GDS) files'
  description: |
    This package provides a high-level R interface to CoreArray Genomic Data Structure
    (GDS) data files, which are portable across platforms with hierarchical structure
    to store multiple scalable array-oriented data sets with metadata information.
    It is suited for large-scale datasets, especially for data which are much larger
    than the available random-access memory. The gdsfmt package offers the efficient
    operations specifically designed for integers of less than 8 bits, since a diploid
    genotype, like single-nucleotide polymorphism (SNP), usually occupies fewer bits
    than a byte. Data compression and decompression are available with relatively
    efficient random access. It is also allowed to read a GDS file in parallel with
    multiple R processes supported by the package parallel.
  license_family: LGPL
