{% set version = "1.2.11" %}
{% set name = "GenomeInfoDbData" %}
{% set bioc = "3.18" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 2a4cbfc2031992fed3c9445f450890a2
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - r-base
  run:
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/annotation/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Species and taxonomy ID look up tables used by GenomeInfoDb'
  description: 'Files for mapping between NCBI taxonomy ID and species. Used by functions in the GenomeInfoDb package.'
extra:
  parent_recipe:
    name: bioconductor-genomeinfodbdata
    path: recipes/bioconductor-genomeinfodbdata
    version: 1.1.0

