{% set version = '0.1.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ttservice
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ttservice_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ttservice/ttservice_{{ version }}.tar.gz
  sha256: 1c08a25cf4ca6a563ddd5c04f96cc0c017a5ab5f4eb69a8cc423c1be615f4d73

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ttservice')"           # [not win]
    - "\"%R%\" -e \"library('ttservice')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=ttservice
  license: GPL-3
  summary: It provides generic methods that are used by more than one package, avoiding conflicts.
    This package will be imported by 'tidySingleCellExperiment' and 'tidyseurat'. The
    implemented method is join_features().
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: ttservice
# Type: Package
# Title: A Service for Tidy Transcriptomics Software Suite
# Version: 0.1.2
# Authors@R: c(person("Stefano", "Mangiola", email = "mangiolastefano@gmail.com", role = c("aut", "cre")) )
# Description: It provides generic methods that are used by more than one package, avoiding conflicts. This package will be imported by 'tidySingleCellExperiment' and 'tidyseurat'. The implemented method is join_features().
# License: GPL-3
# Depends: R (>= 4.0.0)
# Imports: methods
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-10-12 07:00:31 UTC; mangiola.s
# Author: Stefano Mangiola [aut, cre]
# Maintainer: Stefano Mangiola <mangiolastefano@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-10-12 12:30:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
