{% set name = "r-seuratdisk" %}
{% set version = "0.0.9020" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mojaveazure/seurat-disk
  git_rev: 9b89970eac2a3bd770e744f63c7763419486b14c  # on 2022.04.22

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
    host:
        - r-seurat
        - r-devtools
        - r-crayon
        - r-hdf5r
        - r-matrix
        - r-r6
        - r-rlang
        - r-stringi
        - r-withr
    run:
        - r-seurat
        - r-crayon
        - r-hdf5r
        - r-matrix
        - r-r6
        - r-rlang
        - r-stringi
        - r-withr
        - r-spatstat.core
        - r-spatstat

test:
    commands:
        - $R -e 'library(Seurat)'
        - $R -e 'library(SeuratDisk)'

about:
  home: https://github.com/mojaveazure/seurat-disk
  dev_url: https://github.com/mojaveazure/seurat-disk
  license: GPL-3.0-only
  license_file: LICENSE
  summary: 'Support for multi-modal single cell through h5Seurat and AnnData for Seurat'
  description: |
        The h5Seurat file format is specifically designed for the storage and
        analysis of multi-modal single-cell and spatially-resolved expression
        experiments, for example, from CITE-seq or 10X Visium technologies. It
        holds all molecular information and associated metadata, including (for
        example) nearest-neighbor graphs, dimensional reduction information,
        spatial coordinates and image data, and cluster labels. We also support
        rapid and on-disk conversion between h5Seurat and AnnData objects,
        with the goal of enhancing interoperability between Seurat and Scanpy.
  license_family: GPL
